# Hello World

name: Hello World
start: 1

question: 1; What is your favorite color?
# This 3 answers will jump to question 2
answer: 1; Red; 2
answer: 1; Blue; 2
answer: 1; Green; 2
# This answer will jump to question 3
answer: 1; Yellow; 3
question: 2; What is your favorite animal?
answer: 2; Dog; 3
answer: 2; Cat; 3
answer: 2; Bird; 3
# This answer will jump to end 1101
answer: 2; Fish; 1101
question: 3; What is your favorite food?
# This 2 answers will jump to end 1102
answer: 3; Pizza; 1102
answer: 3; Pasta; 1102
# This 2 answers will jump to end 1103
answer: 3; Salad; 1103
answer: 3; Soup; 1103

end: 1101; You like fish!
end: 1102; End number 2
end: 1103; End number 3
