# Тестовый опрос

name: Тестовый опрос
start: 1

question: 1; Какой стебель у растения?
answer: 1; Зелёный; 99; action: data.Type = 1
answer: 1; Древесный; 2
question: 2; Каково положение стебля?
answer: 2; Стелящееся; 99; action: data.Type = 2
answer: 2; Прямостоящее; 3
question: 3; Имеет ли растение один основной ствол?
answer: 3; Да; 4; action: data.Type = 4
answer: 3; Нет; 99; action: data.Type = 3
question: 4; Имеют ли листья широкую и плоскую форму листа?
answer: 4; Да; 99; action: data.Class = 1
answer: 4; Нет; 5; action: data.Class = 2
question: 5; Какова форма листа?
answer: 5; Чешуеобразная; 99; action: data.Family = 1
answer: 5; Иглоподобная; 6
question: 6; Какова конфигурация расположения игл?
answer: 6; Хаотическая; 99; action: data.Family = 2
answer: 6; В 2 ряда; 7
question: 7; Имеется ли серебристая полоса снизу иглы?
answer: 7; Да; 99; action: data.Family = 2
answer: 7; Нет; 99; action: data.Family = 3

end: 99; *data
