# Лабораторная работа №6 Юля

name: Лабораторная работа №6
start: 1

question: 1; Какая погода на улице?
answer: 1; Хорошая; 2
answer: 1; Плохая; 5
question: 2; Где планируется провести досуг?
answer: 2; На улице; 3
answer: 2; В помещении; 5
question: 3; Каков бюджет для проведения досуга?
answer: 3; Платно; 4
answer: 3; Бесплатно; 13
question: 4; Как хотим провести время?
answer: 4; Активно; 11
answer: 4; Пассивно; 12

question: 5; Досуг проводится дома?
answer: 5; Да; 7
answer: 5; Нет; 9
question: 6; Какой тип досуга планируется?
answer: 6; Образовательный; 14
answer: 6; Развлекательный; 15
question: 7; Досуг является творческим?
answer: 7; Да; 16
answer: 7; Нет; 8
question: 8; Нужен ли гаджет для досуга?
answer: 8; Гаджет нужен; 17
answer: 8; Гаджет не нужен; 9
question: 9; Какой тип игры?
answer: 9; Не азартная; 18
answer: 9; Азартная; 19

end: 11; Туризм
end: 12; Посещение зоопарка xD
end: 13; Прогулка
end: 14; Музей
end: 15; Кинотеатр
end: 16; Рисование
end: 17; Просмотр сериалов
end: 18; Сбор пазлов
end: 19; Настольные игры
