# Лабораторная работа №6 Юля

name: Лабораторная работа №6
start: 1

question: 1; Каков бюджет для просмотра видеоресура?
answer: 1; Платно; 2
answer: 1; Бесплатно; 3
question: 2; Что хотим смотреть?
answer: 2; Сериалы; 11
answer: 2; Не сериалы; 12

question: 3; Какая длительность?
answer: 3; Длинные; 4
answer: 3; Короткие; 5
question: 4; Контент для детей?
answer: 4; Да; 13
answer: 4; Нет; 6
question: 5; Регион проживания?
answer: 5; РФ; 17
answer: 5; Не РФ; 16
question: 6; Смотрим кино?
answer: 6; Да; 14
answer: 6; Нет; 15

end: 11; Сериалы: start
end: 12; Фильмы: Иви
end: 13; Мультфильмы: Кинопоиск
end: 14; Фильмы: Кинопоиск
end: 15; Видео: YouTube
end: 16; Короткие видео: Тикток
end: 17; Короткие видео: Ютуб шортс
